services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile.production
    image: swapi-mern-example-api-prod:latest
    volumes: []
    command: pnpm --filter api start

  pwa:
    build:
      context: .
      dockerfile: packages/pwa/Dockerfile.production
    image: swapi-mern-example-pwa-prod:latest
    volumes: []
    command: nginx -g "daemon off;"
